'use client';
import { useState,useCallback } from "react";
import { MdKeyboardArrowDown, MdInfoOutline } from "react-icons/md";
import ConsumedFuel from "./Consumed-fuel/Consumed-fuel";
import { GlobalState } from "../../../../../Context/page";
import { Tooltip as ReactTooltip } from 'react-tooltip';
import 'react-tooltip/dist/react-tooltip.css'
import Purchased from "./Purchased/purchased";
import Selfgenerated from "./Self-generated/self-generated"
import Energysold from "./Energy-sold/energy-sold"
import Standards from "./Standards/standards"
import Source from "./Source/source";
const AccordionItem = ({ title, children, tooltiptext, sdg, display,location,setLocationMessage,year  }) => {
  const [isOpen, setIsOpen] = useState(false);
  const { open } = GlobalState();
  const handleClick = () => {
    if (!location) {
      setLocationMessage("Please select a location and year")

      return;
    }
    setIsOpen(!isOpen);
  };
  return (
    <div className={`shadow-md py-1 mb-4 rounded-[8px] cursor-pointer border border-b-3 border-neutral-200 ${open ? "w-[100%]" : "w-[100%]"}`}>
      <button
        className="py-3 w-[100%] text-left flex"
        onClick={handleClick}// Unique ID for the tooltip, spaces replaced by dashes
      >
        <div className="flex justify-between">
        <div className={`flex ${open ? "w-[65vw]" : "w-[74vw]"}`}>
        <div className="flex items-center">
          <h5 className="text-[14px] text-[#344054] px-3">{title}</h5>
        </div>

        <div className="flex items-center justify-center relative">
          <MdInfoOutline
            data-tooltip-id={`tooltip-${title.replace(/\s+/g, '-')}`} data-tooltip-content={tooltiptext} className="mt-1 text-[14px]" style={{display:display}} />
          {/* Tooltip */}
          <ReactTooltip id={`tooltip-${title.replace(/\s+/g, '-')}`} place="top" effect="solid" style={{
            width: "300px", backgroundColor: "#000",
            color: "white",
            fontSize: "12px",
            boxShadow: 3,
            borderRadius: "8px",
          }}>

          </ReactTooltip>
        </div>
        </div>
       <div className=" w-[20vw] ">
       <div className={`flex float-end`}>
        {isOpen ? (
            <>
              {sdg && sdg.map((sdgItem, index) => (
                <div key={index} className="bg-sky-100 h-[25px] w-[70px] rounded-md mx-2" style={{ display: display }} >
                  <p className="text-[#0057A5] text-[10px] inline-block align-middle px-2 font-semibold">{sdgItem}</p>
                </div>
              ))}
            </>
          ) : (
            <>
              {sdg && sdg.map((sdgItem, index) => (
                <div key={index} className="bg-sky-100 h-[25px] w-[70px] rounded-md mx-2">
                  <p className="text-[#0057A5] text-[10px] inline-block align-middle px-2 font-semibold">{sdgItem}</p>
                </div>
              ))}
            </>
          )}
          <MdKeyboardArrowDown className={`text-2xl ${isOpen ? "rotate-180" : ""}`} />
        </div>
       </div>
        </div>


      </button>
      {isOpen && <div className="p-4">{children}</div>}
    </div>
  );
};

const EnergyConsumedBody = ({location, year, month,setLocationMessage}) => {

  return (
    <>
      <div className="mx-3">
      <AccordionItem
       title="Direct Purchased Heating, Cooling, Electricity and Steam"
          tooltiptext={`This section documents data corresponding to Energy Purchased
          for use within the Organization. Include: Input data related only
          to directly purchased heating, electricity, steam and cooling inside
           the organization.  Exclude: Do not include data relating to fuel consumption. `}
          sdg={['GRI 302-1a', 'GRI 302-1b']}
          display="block"
          location={location}
          setLocationMessage={setLocationMessage}
        >
          <Purchased  location={location} year={year} month={month}/>
        </AccordionItem>
        <AccordionItem
          title="Consumed fuel and energy, including self generated"
          tooltiptext={`This section documents data corresponding to energy consumed - including fuels.
          Include:
          Self-Generated Energy shall be incorporated in this context.
          Exclude: Direct purchased Heating, Cooling, Electricity, and Steam.`}
          sdg={['GRI 302-1c', 'GRI 302-1e']}
          display="block"
          location={location}
          setLocationMessage={setLocationMessage}
        >
          <ConsumedFuel location={location} year={year} month={month}/>
        </AccordionItem>
        <AccordionItem
       title="Self generated - not consumed or sold"
          tooltiptext={`This section documents data corresponding to energy
          generated by the organization (self-generated energy) that
          remains unconsumed or unsold.`}
           sdg={['GRI 302-1']}
           display="block"
           location={location}
           setLocationMessage={setLocationMessage}
        >
          <Selfgenerated location={location} year={year} month={month}/>
        </AccordionItem>
        <AccordionItem
       title="Energy sold"
          tooltiptext={`This section documents data corresponding
          to energy that is sold, regardless of whether
          it is procured or self-generated. `}
          sdg={['GRI 302-1d']}
          display="block"
          location={location}
          setLocationMessage={setLocationMessage}
        >
          <Energysold location={location} year={year} month={month}/>
        </AccordionItem>
        <AccordionItem
       title="Standards, methodologies, assumptions and calculation tools used"
          tooltiptext={`Standards, methodologies, assumptions and calculation tools used`}
          sdg={['GRI 302-1f']}
          display="none"
          location={location}
          setLocationMessage={setLocationMessage}
        >
          <Standards location={location} year={year} month={month}/>
        </AccordionItem>
        <AccordionItem
       title="Source of  conversion factor"
          tooltiptext={`Source of  conversion factor `}
          sdg={['GRI 302-1g']}
          display="none"
          location={location}
          setLocationMessage={setLocationMessage}
        >
          <Source  location={location} year={year} month={month}/>
        </AccordionItem>
        {/* Add more accordion items here */}
      </div>

    </>
  );
};

export default EnergyConsumedBody;
