
const optionsMap = {
MitigationStrategies: {
    "Extreme weather events": [
        "Installation of early warning systems",
        "Community engagement and education",
        "Investment in resilient infrastructure",
        "Enhanced weather monitoring",
        "Flood defenses",
        "Improved drainage systems",
        "Structural reinforcements",
        "Emergency preparedness programs",
        "Backup power systems",
        "Others (please specify)",
      ],
    "Temperature changes": [
        "Energy-efficient technologies",
        "Employee training on energy conservation",
        "Real-time temperature monitoring",
       "Insulation upgrades",
        "High-efficiency HVAC systems",
        "Shade structures",
        "Green roofs",
        "Energy management systems",
        "Others (please specify)",
    ],

    "Sea level rise": [
        "Development of flood-resistant buildings",
        "Community relocation programs",
        "Continuous risk assessment and adaptation",
        "Raised buildings",
        "Wetland restoration",
        "Coastal zoning regulations",
        "Others (please specify)",
    ],
    "Water scarcity": [
        "Installation of water-efficient fixtures",
        "Development of drought-resistant crops",
        "Implementation of water rationing",
        "Community water-saving programs",
        "Rainwater harvesting",
        "Greywater systems",
        "Desalination plants",
        "Xeriscaping",
        "Water-efficient irrigation systems",
        "Others (please specify)",
    ],
    "Changes in precipitation patterns": [
        "Implementation of adaptive farming techniques",
        "Enhanced water storage infrastructure",
        "Real-time precipitation monitoring",
        "Community risk awareness",
        "Floodplain zoning",
        "Improved stormwater systems",
        "Agricultural diversification",
        "Advanced forecasting models",
        "Rainwater capture systems",
        "Others (please specify)",
    ],
    "Natural disasters": [
        "Investment in disaster-resilient infrastructure",
        "Continuous community education and drills",
        "Real-time disaster monitoring systems",
        "Robust communication systems",
        "Earthquake-resistant structures",
        "Firebreaks",
        "Flood barriers",
        "Emergency shelters",
        "Real-time alert systems",
        "Others (please specify)",
    ],
    "Air Quality Degradation": [
        "Implementation of air filtration systems",
        "Upgrading to cleaner fuel sources",
        "Adoption of renewable energy sources",
        "Installation of advanced ventilation systems",
        "Urban greening and tree planting",
        "Use of low-emission industrial processes",
        "Indoor air quality monitoring and improvement",
        "Others (please specify)",
    ],

    "Heatwaves": [
        "Installation of air conditioning systems",
        "Shading and ventilation improvements",
        "Employee wellness programs",
        "Real-time temperature monitoring",
        "Community engagement",
        "Others (please specify)",
    ],
    "Regulatory changes": [
        "Regular compliance audits",
        "Stakeholder engagement",
        "Adoption of best practices",
        "Continuous improvement programs",
        "Others (please specify)",
    ],
    "Market shifts": [
        "Market diversification",
        "Product innovation",
        "Customer feedback mechanisms",
        "Market trend analysis",
        "Others (please specify)",
    ],
    "Technology changes": [
        "Adoption of new technologies",
        "Continuous training programs",
        "Strategic innovation initiatives",
        "Real-time monitoring",
        "Others (please specify)",
    ],
    "Reputational risks": [
        "Crisis communication plans CSR activities",
        "Regular stakeholder updates",
        "Others (please specify)",
    ],
    "Legal Risks": [
        "Regular legal audits",
        "Risk mitigation strategies",
        "Legal awareness training",
        "Effective dispute resolution",
        "Others (please specify)",
    ],
    "Energy transition": [
        "Adoption of renewable energy",
        "Implementation of energy-saving technologies",
        "Sustainability reporting",
        "Carbon offset programs",
        "Others (please specify)",
      ],
      "Consumer Preference Changes": [
        "Launch eco-friendly product lines",
        "Implement sustainable supply chain practices",
        "Enhance product transparency",
        "Develop recycling programs",
        "Increase investment in R&D for sustainable innovations",
        "Create loyalty programs for green products",
        "Others (please specify)",
        
      ],
      "Supply chain disruptions": [
        "Develop contingency plans for supply chain interruptions",
        "Establish alternative sourcing strategies",
        "Enhance logistics and distribution networks",
        "Implement supplier audits and compliance checks",
        "Strengthen partnerships with key suppliers",
        "Use technology for supply chain visibility",
        "Others (please specify)",
        
      ],
      "Corporate governance changes": [
        "Implement governance risk assessments",
        "Enhance internal controls and audit processes",
        "Improve board diversity and independence",
        "Establish clear governance structures",
        "Develop whistleblower programs",
        "Strengthen oversight and accountability mechanisms",
        "Others (please specify)",
        
      ],
  },
};