'use client'
import { useState, useRef, useEffect } from "react";
import WasteTable from "../tables/waterTable";


const Section25=({section12_5_2Ref})=>{
    const [content,setContent] = useState(
        `We set targets for reducing energy consumption and implement various initiatives, such as upgrading equipment, improving insulation, and optimizing processes to achieve these goals.`
    )


      const column1 = [
        'Material Type', 
        'Contribution %', 
        "Total in Qty",
        'Unit'
      ];
      const data1 = [
        {
            "Material Type": 'data',
          'Contribution %': 'data',
          "Total in Qty":"data",
        'Unit':"data"
        },
      ];


      const column2 = [
        'Location', 
        'Material Type', 
        'Contribution %',
        'Qty of total waste', 
        'Unit'
      ];
      const data2 = [
        {
            "Location": 'data',
          'Material Type': 'data',
        'Contribution %':"data",
         'Qty of total waste': 'data',
        'Unit':"data"
        },
      ];


      const column3 = [
        'Total Waste by Category', 
        'Contribution %',
        'Total in Qty', 
        'Unit'
      ];
      const data3 = [
        {
            "Total Waste by Category": 'data',
        'Contribution %':"data",
         'Total in Qty': 'data',
        'Unit':"data"
        },
      ];


     
      
    
    return (
        <>
       
        <div id="section12_5_2" ref={section12_5_2Ref}>

<h3 className="text-[15px] text-[#344054] mb-4 text-left font-semibold">
12.5.2  Waste Generation and Impacts
</h3>

        
<p className="text-[15px]  mb-2 font-semibold">
We track and report the amount and type of waste generated by our operations. Our goal is to reduce waste generation through process improvements and waste reduction initiatives. 

        </p>
        <p className="text-[15px]  mb-2 font-semibold">
        Inputs, activities, and outputs that lead or could lead to waste-related impacts: 


        </p>
        <p className="text-sm mb-4">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores quisquam, culpa modi dicta tenetur, ducimus vero labore, commodi voluptates dolorum perferendis atque? Ipsum saepe obcaecati temporibus similique maxime modi corporis?</p>
        <p className="text-[15px]  mb-2 font-semibold">
        Impacts relate to waste generated in the organization’s own activities or to waste generated upstream or downstream in its value chain.:

        </p>
        <p className="text-sm mb-4">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores quisquam, culpa modi dicta tenetur, ducimus vero labore, commodi voluptates dolorum perferendis atque? Ipsum saepe obcaecati temporibus similique maxime modi corporis?</p>

        <p className="text-[15px]  mb-2 font-semibold">
        Waste generated by material

        </p>
<div className="shadow-md rounded-md mb-4">
<WasteTable columns={column1} data={data1} consumption="Total" unit={"Metric tons (t)"} total={'212123545'}/>
</div>

<p className="text-[15px]  mb-2 font-semibold">
Waste Generated by Location
        </p>
<div className="shadow-md rounded-md mb-4">
<WasteTable columns={column2} data={data2} consumption="Total" unit={"Metric tons (t)"} total={'212123545'}/>
</div>

<p className="text-[15px]  mb-2 font-semibold">
Hazardous and Non-Hazardous waste composition
        </p>
<div className="shadow-md rounded-md mb-4">
<WasteTable columns={column3} data={data3} consumption="Total" unit={"Metric tons (t)"} total={'212123545'}/>
</div>


</div>
        </>
    )
}

export default Section25