import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalStateProvider } from "../Context/page";
import { AuthProvider } from "../Context/auth";
import { ToastContainer } from 'react-toastify';
import 'react-tooltip/dist/react-tooltip.css';
export const metadata = {
  title: "Sustainext",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap"
          rel="stylesheet"
        ></link>
      </head>

      <body>
      <ToastContainer style={{ fontSize: "12px" }} />
        <GlobalStateProvider>
          <AuthProvider>{children}</AuthProvider>
        </GlobalStateProvider>
      </body>
    </html>
  );
}
