import React, { useState, useEffect } from "react";
import { AiOutlineLink } from "react-icons/ai";

const TableSidebar = () => {
  const [activeId, setActiveId] = useState("");

  const adjustScrollPosition = (anchor) => {
    const headerOffset = 250;
    const elementPosition = document.querySelector(anchor).getBoundingClientRect().top;
    const offsetPosition = elementPosition + window.pageYOffset - headerOffset;

    window.scrollTo({
      top: offsetPosition,
      behavior: "smooth",
    });
  };

  useEffect(() => {
    const handleScroll = () => {
      const links = [
        "waste1",
        "waste2",
        "waste3",
        "waste4",
        "waste5",
        "waste6",
        "waste7",
        "waste8",
        "waste9",
        "waste10",

      ];

      const threshold = 150;

      for (const id of links) {
        const element = document.getElementById(id);
        if (element) {
          const rect = element.getBoundingClientRect();
          if (rect.top >= -threshold && rect.top <= window.innerHeight - threshold) {
            setActiveId(id);
            break;
          }
        }
      }
    };

    window.addEventListener("scroll", handleScroll, { passive: true });

    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  return (
    <div className="w-[199px] h-[580px] pl-[17px] pr-[21px] py-[21px] rounded-lg border flex-col justify-start items-end gap-2 inline-flex">
      <div className="w-[161px] justify-end items-center gap-2 inline-flex">
        <div className="text-right text-neutral-500 text-[10px] font-semibold font-['Manrope'] leading-[14px] tracking-wide">
          Tables
        </div>
      </div>
      {[
        {
          id: "waste1",
          name: "Waste generated by material",
        },
        {
          id: "waste2",
          name: "Waste Generated by Location",
        },
        {
          id: "waste3",
          name: "Hazardous and Non-Hazardous waste composition",
        },
        {
          id: "waste4",
          name: "Waste  directed to disposal by material type",
        },
        {
          id: "waste5",
          name: "Waste diverted from disposal by material type",
        },
        {
          id: "waste6",
          name: "Hazardous waste diverted form disposal",
        },
        {
          id: "waste7",
          name: "Non-hazardous waste diverted form disposal",
        },
        {
          id: "waste8",
          name: "Hazardous waste directed to disposal",
        },
        {
          id: "waste9",
          name: "Non-hazardous waste directed to disposal",
        },


      ].map((link) => (
        <div key={link.id} className="self-stretch justify-end items-center gap-2 inline-flex">
          <a
            href={`#${link.id}`}
            onClick={(e) => {
              e.preventDefault();
              adjustScrollPosition(`#${link.id}`);
            }}
            className={`grow shrink basis-0 text-right ${
              activeId === link.id ? "text-teal-500 font-semibold" : "text-sky-600"
            } text-[10px] font-normal font-['Manrope'] leading-[14px] hover:text-teal-500`}
          >
            <AiOutlineLink className="inline-block mr-1" />
            {link.name}
          </a>
        </div>
      ))}
    </div>
  );
};

export default TableSidebar;
